language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk9

before_install:
  - curl -s api.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh
  - sdk list gradle
  - sdk install gradle 5.6.1
  - sdk default gradle 5.6.1